In [ ]:
# Developed by SinaSeifouri
# Github: SinaSOX
# Dataset URL: https://www.kaggle.com/datasets/sulianova/cardiovascular-disease-dataset

In [1]:
import pandas as pd
import tensorflow as tf

In [9]:
data = pd.read_csv('./cardio_train.csv',delimiter=";",index_col="id")
data

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
id                                                                             
0      18393       2     168    62.0    110     80            1     1      0   
1      20228       1     156    85.0    140     90            3     1      0   
2      18857       1     165    64.0    130     70            3     1      0   
3      17623       2     169    82.0    150    100            1     1      0   
4      17474       1     156    56.0    100     60            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
99993  19240       2     168    76.0    120     80            1     1      1   
99995  22601       1     158   126.0    140     90            2     2      0   
99996  19066       2     183   105.0    180     90            3     1      0   
99998  22431       1     163    72.0    135     80            1     2      0   
99999  20540       1     170    72.0    120     80            2     1      0   

       alco  active  cardio  
id                           
0         0       1       0  
1         0       1       1  
2         0       0       1  
3         0       1       1  
4         0       0       0  
...     ...     ...     ...  
99993     0       1       0  
99995     0       1       1  
99996     1       0       1  
99998     0       0       1  
99999     0       1       0  

[70000 rows x 12 columns]

In [15]:
data.isna().sum()

age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [16]:
data.describe()

age        gender        height        weight         ap_hi  \
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000   
mean   19468.865814      1.349571    164.359229     74.205690    128.817286   
std     2467.251667      0.476838      8.210126     14.395757    154.011419   
min    10798.000000      1.000000     55.000000     10.000000   -150.000000   
25%    17664.000000      1.000000    159.000000     65.000000    120.000000   
50%    19703.000000      1.000000    165.000000     72.000000    120.000000   
75%    21327.000000      2.000000    170.000000     82.000000    140.000000   
max    23713.000000      2.000000    250.000000    200.000000  16020.000000   

              ap_lo   cholesterol          gluc         smoke          alco  \
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000   
mean      96.630414      1.366871      1.226457      0.088129      0.053771   
std      188.472530      0.680250      0.572270      0.283484      0.225568   
min      -70.000000      1.000000      1.000000      0.000000      0.000000   
25%       80.000000      1.000000      1.000000      0.000000      0.000000   
50%       80.000000      1.000000      1.000000      0.000000      0.000000   
75%       90.000000      2.000000      1.000000      0.000000      0.000000   
max    11000.000000      3.000000      3.000000      1.000000      1.000000   

             active        cardio  
count  70000.000000  70000.000000  
mean       0.803729      0.499700  
std        0.397179      0.500003  
min        0.000000      0.000000  
25%        1.000000      0.000000  
50%        1.000000      0.000000  
75%        1.000000      1.000000  
max        1.000000      1.000000

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   age          70000 non-null  int64  
 1   gender       70000 non-null  int64  
 2   height       70000 non-null  int64  
 3   weight       70000 non-null  float64
 4   ap_hi        70000 non-null  int64  
 5   ap_lo        70000 non-null  int64  
 6   cholesterol  70000 non-null  int64  
 7   gluc         70000 non-null  int64  
 8   smoke        70000 non-null  int64  
 9   alco         70000 non-null  int64  
 10  active       70000 non-null  int64  
 11  cardio       70000 non-null  int64  
dtypes: float64(1), int64(11)
memory usage: 6.9 MB


In [70]:
from sklearn.preprocessing import MinMaxScaler

In [85]:
X = data.loc[:,'age':'active':1]
X

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
id                                                                             
0      18393       2     168    62.0    110     80            1     1      0   
1      20228       1     156    85.0    130     90            3     1      0   
2      18857       1     165    64.0    130     70            3     1      0   
3      17623       2     169    82.0    150    100            1     1      0   
4      17474       1     156    56.0    100     60            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
99993  19240       2     168    76.0    120     80            1     1      1   
99995  22601       1     158   126.0    140     90            2     2      0   
99996  19066       2     183   105.0    180     90            3     1      0   
99998  22431       1     163    72.0    135     80            1     2      0   
99999  20540       1     170    72.0    120     80            2     1      0   

       alco  active  
id                   
0         0       1  
1         0       1  
2         0       0  
3         0       1  
4         0       0  
...     ...     ...  
99993     0       1  
99995     0       1  
99996     1       0  
99998     0       0  
99999     0       1  

[70000 rows x 11 columns]

In [72]:
minmax_model = MinMaxScaler()

In [75]:
transformed_x = minmax_model.fit_transform(X)

In [74]:
Y = data.loc[:,'cardio']
Y

id
0        0
1        1
2        1
3        1
4        0
        ..
99993    0
99995    1
99996    1
99998    1
99999    0
Name: cardio, Length: 70000, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [76]:
x_train,x_test,y_train,y_test = train_test_split(transformed_x,Y,shuffle=True,random_state=79,test_size=0.3)

In [80]:
type(x_train)

numpy.ndarray

In [83]:
len(x_train)

49000

In [150]:
model = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=11),
    tf.keras.layers.Dense(40,activation='relu'),
    tf.keras.layers.Dense(20,activation='relu'),
    tf.keras.layers.Dense(10,activation='relu'),
    tf.keras.layers.Dense(1,activation="sigmoid")
])

In [155]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.BinaryCrossentropy(),metrics=tf.keras.metrics.CategoricalAccuracy())

In [156]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_29 (Dense)            (None, 40)                480       
                                                                 
 dense_30 (Dense)            (None, 20)                820       
                                                                 
 dense_31 (Dense)            (None, 10)                210       
                                                                 
 dense_32 (Dense)            (None, 1)                 11        
                                                                 
Total params: 1,521
Trainable params: 1,521
Non-trainable params: 0
_________________________________________________________________


In [162]:
model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),batch_size=100)

Epoch 1/50
490/490 [==============================] - 1s 2ms/step - loss: 9.8674 - categorical_accuracy: 1.0000 - val_loss: 6.6394 - val_categorical_accuracy: 1.0000
Epoch 2/50
490/490 [==============================] - 1s 2ms/step - loss: 3.2687 - categorical_accuracy: 1.0000 - val_loss: 1.4293 - val_categorical_accuracy: 1.0000
Epoch 3/50
490/490 [==============================] - 1s 2ms/step - loss: 1.1658 - categorical_accuracy: 1.0000 - val_loss: 0.9778 - val_categorical_accuracy: 1.0000
Epoch 4/50
490/490 [==============================] - 1s 2ms/step - loss: 0.8784 - categorical_accuracy: 1.0000 - val_loss: 0.7930 - val_categorical_accuracy: 1.0000
Epoch 5/50
490/490 [==============================] - 1s 2ms/step - loss: 0.7480 - categorical_accuracy: 1.0000 - val_loss: 0.7108 - val_categorical_accuracy: 1.0000
Epoch 6/50
490/490 [==============================] - 1s 2ms/step - loss: 0.6966 - categorical_accuracy: 1.0000 - val_loss: 0.6838 - val_categorical_accuracy: 1.0000
Epoc

In [174]:
model.predict(np.array([x_train[1]]))

1/1 [==============================] - 0s 26ms/step


array([[0.63958615]], dtype=float32)

In [172]:
import numpy as np

In [173]:
np.array([x_train[1]])

array([[0.95323268, 0.        , 0.55384615, 0.29473684, 0.01669759,
        0.01355014, 0.        , 0.        , 0.        , 0.        ,
        1.        ]])

In [167]:
x_train

array([[0.6789005 , 1.        , 0.54871795, ..., 0.        , 0.        ,
        1.        ],
       [0.95323268, 0.        , 0.55384615, ..., 0.        , 0.        ,
        1.        ],
       [0.69516067, 0.        , 0.57948718, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.40170345, 0.        , 0.57948718, ..., 0.        , 0.        ,
        1.        ],
       [0.74974835, 0.        , 0.55897436, ..., 0.        , 0.        ,
        0.        ],
       [0.29407666, 0.        , 0.61538462, ..., 0.        , 0.        ,
        0.        ]])

In [176]:
# way 2 - One Hot Encoding of target

In [177]:
Y = data.loc[:,'cardio']
Y

id
0        0
1        1
2        1
3        1
4        0
        ..
99993    0
99995    1
99996    1
99998    1
99999    0
Name: cardio, Length: 70000, dtype: int64

In [181]:
transformed_y = pd.get_dummies(Y)
transformed_y

0  1
id         
0      1  0
1      0  1
2      0  1
3      0  1
4      1  0
...   .. ..
99993  1  0
99995  0  1
99996  0  1
99998  0  1
99999  1  0

[70000 rows x 2 columns]

In [188]:
x_train_ohe,x_test_ohe,y_train_ohe,y_test_ohe = train_test_split(transformed_x,transformed_y,shuffle=True,random_state=79,test_size=0.3)

In [192]:
model_ohe = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=11),
    tf.keras.layers.Dense(40,activation='relu'),
    tf.keras.layers.Dense(20,activation='relu'),
    tf.keras.layers.Dense(10,activation='relu'),
    tf.keras.layers.Dense(2,activation="softmax")
])

In [193]:
model_ohe.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.CategoricalCrossentropy(),metrics=tf.keras.metrics.CategoricalAccuracy())

In [194]:
model_ohe.fit(x_train_ohe,y_train_ohe,epochs=50,validation_data=(x_test_ohe,y_test_ohe),batch_size=100)

Epoch 1/50
490/490 [==============================] - 2s 3ms/step - loss: 0.6471 - categorical_accuracy: 0.6180 - val_loss: 0.6356 - val_categorical_accuracy: 0.6383
Epoch 2/50
490/490 [==============================] - 1s 2ms/step - loss: 0.6319 - categorical_accuracy: 0.6399 - val_loss: 0.6278 - val_categorical_accuracy: 0.6465
Epoch 3/50
490/490 [==============================] - 1s 3ms/step - loss: 0.6282 - categorical_accuracy: 0.6456 - val_loss: 0.6292 - val_categorical_accuracy: 0.6450
Epoch 4/50
490/490 [==============================] - 1s 2ms/step - loss: 0.6263 - categorical_accuracy: 0.6475 - val_loss: 0.6261 - val_categorical_accuracy: 0.6473
Epoch 5/50
490/490 [==============================] - 1s 2ms/step - loss: 0.6260 - categorical_accuracy: 0.6471 - val_loss: 0.6301 - val_categorical_accuracy: 0.6441
Epoch 6/50
490/490 [==============================] - 1s 2ms/step - loss: 0.6252 - categorical_accuracy: 0.6464 - val_loss: 0.6242 - val_categorical_accuracy: 0.6520
Epoc

In [197]:
model_ohe.predict(np.array([x_test_ohe[6]]))

1/1 [==============================] - 0s 28ms/step


array([[0.16694523, 0.8330547 ]], dtype=float32)